[package]
name = "modelatorc"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
authors = [
  "Ranadeep Biswas <ranadeep@informal.systems>",
]

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.55"
modelator = { path = ".." }
serde_json = "1.0.79"
