[package]
name = "modelator"
description = "A framework and tools for model-based testing."
version = "0.1.0"
edition = "2018"
license    = "Apache-2.0"
readme     = "README.md"
keywords   = ["testing", "model", "model-based", "TLA", "abstraction"]
repository = "https://github.com/informalsystems/modelator"
authors = [
    "Vitor Enes <vitorenesduarte@gmail.com>", 
    "Andrey Kuprianov <andrey@informal.systems>"
]

[dependencies]
clap = "3.0.0-beta.2"
hex = "0.4.3"
nom = "6.1.2"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
sha2 = "0.9.3"
thiserror = "1.0.24"
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
ureq = "2.1.0"

[dev-dependencies]
once_cell = "1.7.2"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
